/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fcjCdqhDfF8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function AddPostFrame() {
  return (
    <div className="max-w-2xl mx-auto p-6 md:p-8">
      <div className="grid gap-6">
        <div className="grid gap-1">
          <h1 className="text-3xl font-bold">Create New Product</h1>
          <p className="text-gray-500 dark:text-gray-400">Fill out the form to add a new product to your inventory.</p>
        </div>
        <form className="grid gap-6">
          <div className="grid gap-2">
            <Label htmlFor="name">Product Name</Label>
            <Input id="name" placeholder="Enter product name" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="price">Price</Label>
            <Input id="price" placeholder="Enter price" type="number" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="description">Description</Label>
            <Textarea id="description" placeholder="Enter product description" rows={4} />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="category">Category</Label>
            <Select defaultValue="select" id="category">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select category" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="clothing">Clothing</SelectItem>
                <SelectItem value="electronics">Electronics</SelectItem>
                <SelectItem value="home">Home & Garden</SelectItem>
                <SelectItem value="toys">Toys & Games</SelectItem>
                <SelectItem value="sports">Sports & Outdoors</SelectItem>
                <SelectItem value="beauty">Beauty & Personal Care</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="image">Product Image</Label>
            <Input id="image" type="file" />
          </div>
          <Button className="w-full" type="submit">
            Create Product
          </Button>
        </form>
      </div>
    </div>
  )
}
